### ISSUE TITLE
ui.ImageView listed twice in documentation 

### ISSUE THREAD

**Issue by lukaskollmer** [omz/Pythonista-Issues#140] opened 2016-08-08 05:57 UTC
This applies to both the 2.7 and the 3.5 documentation
![](http://cdn.kollmer.me/embed/ui_imageview_twice.png)

**Comment by Phuket2** [comment] 2016-08-08 09:25
As is Label

**Comment by zrzka** [comment] 2017-10-23 11:19
Screenshot missing, anyway, still valid in 311014. The issue is:

* ImageView and Label are listed twice in TOC
* ImageView and Label documentation presented once in the content

So, it's just TOC issue only.

![582ba34f-1340-4e3f-9dd3-79e6b03772e3](https://user-images.githubusercontent.com/1084172/31886470-aabd854a-b7f4-11e7-839a-9fc587eedb8f.jpeg)

**Comment by zrzka** [comment] 2017-10-23 18:48
Dupe of #42.

**Closed by zrzka** 2017-10-23 18:48 UTC
Labels: documentation
