### ISSUE TITLE
Cannot run extension from iCloud

### ISSUE THREAD

**Issue by macta** [omz/Pythonista-Issues#598] opened 2019-02-03 16:21 UTC
When I save my .py extension on iCloud using Pythonista, when I run the extension it always gives me the “script not found” error with a locate button. Using locate I can navigate to my iCloud folder and select it, but I continue to get the error. If I save the script locally on my phone with the example extensions, it then works fine?

I understood I could save on iCloud and then use the script on all my devices?

**Comment by cclauss** [comment] 2019-02-03 16:38
Perhaps this is intentional because of security concerns of running arbitrary code on your device.

**Comment by omz** [comment] 2019-02-03 16:39
No, I think this should be fixed in the current beta.

@macta Are you using the App Store version?

**Comment by macta** [comment] 2019-02-03 16:54
Yes - this is the App Store version. If its something that is known/fixed in future versions then you can close this.

**Comment by dougharris** [comment] 2019-06-18 19:29
Duplicate of #504 (and more comments & explanation in the comments there).

**Comment by cclauss** [comment] 2019-06-18 21:44
Can we close this issue as a dup?

**Closed** 2023-01-26 12:16 UTC
