### ISSUE TITLE
help system action „open in editor“

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#436] opened 2017-10-19 17:18 UTC
Pressing „open in editor“ in help system, does copy the text, but does not open the editor

**Comment by zrzka** [comment] 2017-10-21 14:58
Actually it opens the file named `Example_*.py` in the editor, but the issue is, that the help doesn't hide itself and thus you do not see the opened file / example. Just hide it with Cmd-J and you'll see that these files are there.

**Comment by omz** [comment] 2017-11-12 16:24
Should be fixed in build 311016.

**Closed by omz** 2017-11-12 16:24 UTC
Labels: bug, documentation, pythonista

**Comment by wnMark** [comment] 2017-11-12 17:07
Thank you Ole
