### ISSUE TITLE
tempfiles are *never* cleaned

### ISSUE THREAD

**Issue by controversial** [omz/Pythonista-Issues#73] opened 2016-07-04 19:35 UTC
As far as I can tell, my `tempfile.gettempdir` has never been cleaned. It has survived all the updating through betas and release versions, changes in iOS version, and restarts. It's full of PIL images, even though I haven't shown an image in the console in the last 3 months at least.

Currently,

```
import tempfile, os
print(len(os.listdir(tempfile.gettempdir())))
```

prints `292`. This is a lot of wasted space.

**Comment by lukaskollmer** [comment] 2016-07-04 19:39
@controversial shouldn't iOS take care of this?

**Comment by controversial** [comment] 2016-07-04 19:40
Not sure whether it *should*, but it doesn't seem to. Maybe there's somewhere @omz needs to release the files for iOS to know it can clean them...

**Comment by omz** [comment] 2016-07-04 19:45
In 3.0 and 2.1, images that are shown in the console are automatically deleted when clearing the console, so the space they occupy should be fairly minimal. Previous versions used to write those images to the temp directory in a way that made it difficult to determine where those files actually came from (temporary files could have been created intentionally by your own scripts), so I haven't added any code to delete files from previous versions.

**Comment by omz** [comment] 2016-07-04 19:46
I think iOS _should_ clean up all temporary files eventually, but I'm not completely sure when this happens. It might only be when storage gets low...

**Comment by omz** [comment] 2016-07-04 19:48
Closing this now – as I said, I think the _current_ behavior is fine, and it's difficult to clean up the files that previous versions created.

**Comment by lukaskollmer** [comment] 2016-07-04 19:49
@omz I think iOS deletedsthese temp files after/during system updates, restarts and app updates. Sometimes, apps are grayed out and there is a "Cleaning..." message below the icon.

**Comment by controversial** [comment] 2016-07-04 19:50
@omz a `editor.clear_cache()` function to remove all the temporary files would not be unwarranted, imho. Thanks, though 😀

**Comment by omz** [comment] 2016-07-04 19:55
I take everything back. It looks like the way console images are saved is buggy, and clearing the console actually does _not_ remove them...

**Comment by omz** [comment] 2016-07-04 20:01
After some more investigation, it looks like this _mostly_ works as intended, but is broken for `ui.Image.show` (PIL and matplotlib should be fine).

**Comment by controversial** [comment] 2016-07-04 20:01
😮 smh @omz

**Comment by zrzka** [comment] 2017-10-22 10:31
I think this one can be closed.

* Removed everything from this folder
* `ui.Image.show` -> new file appears in this folder
* Pythonista restart -> folder is empty

Even if anything else stays in this directory, not an issue, these files are not backed up, transferred to the iCloud, ... and system will purge them if there's low space.

To quote docs:

> Use this directory to write temporary files that do not need to persist between launches of your app. Your app should remove files from this directory when they are no longer needed; however, the system may purge this directory when your app is not running. The contents of this directory are not backed up by iTunes or iCloud.

**Closed by zrzka** 2017-10-22 10:31 UTC
Labels: bug, enhancement
