### ISSUE TITLE
File search behaving strangely

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#455] opened 2017-10-25 15:27 UTC
When using file search in 311015:
    1) Searching for a file shows a Test folder -- selecting this then shows search results.  Maybe this is just still test code for the new functionality
    2) Search results are not ordered with preference to results in the current folder.  As an example, if I am browsing site-packages/backend_pythonista, and search for `gestures`, the new system shows me every copy of gestures.py I have, rather than first showng me the one in my current folder!

Desired behavior might be either:
  1) Show matches from current folder only (for speed... maybe I don't want to catalog subfolders in a large tepo, say), but with two additional entries, "Search Subfolders" and " Search entire library".  
or
2) Searching searches everywhere, but results are ordered such that results in current folder are shown first, followed by subfolder results, then finally in the documents folder at large.  Maybe with section headings that make that clear.

**Comment by dgelessus** [comment] 2017-10-25 15:35
Can reproduce, sort of... The real issue seems to be that until the search results have finished loading, the results of the previous search are shown. If you haven't searched in the current folder yet, you see the "Test" folder. Tapping the "Test" folder doesn't actually do anything, I think you're just seeing the delayed loading of the real search results.

Agreed about showing results from the current folder first. It would also be useful if partial search results could be shown while the search is running (with a spinner to show that more results are loading). At the moment if a search takes long, it's not obvious that anything is happening.

**Comment by omz** [comment] 2017-11-12 16:21
Should be fixed in build 311016.

**Closed by omz** 2017-11-12 16:21 UTC
Labels: bug, pythonista
