### ISSUE TITLE
No completions appear behind an attribute access

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#39] opened 2016-06-18 18:50 UTC
For example, behind `print(` and `mystr +` completions appear correctly, but not behind `os.listdir(` or `os.sep +`

**Comment by omz** [comment] 2016-07-04 16:24
This is about completions in the console, right? I can reproduce it there, but it seems to be fine in the editor.

**Comment by dgelessus** [comment] 2016-07-04 16:26
Yes, this is in the console only. Looks like I forgot to write that, sorry.

**Comment by zrzka** [comment] 2017-11-02 08:42
Just tested this in 311015 and I can't reproduce. Closing as fixed. If I'm wrong @dgelessus and you have another special case, just let me know and we can reopen.

**Closed by zrzka** 2017-11-02 08:42 UTC
Labels: bug, pythonista

**Comment by dgelessus** [comment] 2017-11-02 10:14
Yep, it's working now. This was probably fixed a while ago and I forgot to close the issue.
