### ISSUE TITLE
Lots of blank space between sections in top-level file list

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#421] opened 2017-10-17 21:44 UTC
The spacing between the sections in the top-level file list seems unusually big - much larger than the spacing around headers in the iOS Settings app or in Pythonista's settings for example.

This is even more visible if the favorites and/or recent external files list is empty, because those lists include a small separator at the top - and when the lists are empty, that separator merges with the large spacing below, making it even larger.

This is on iOS 10, if it makes a difference.

**Comment by omz** [comment] 2017-10-18 09:15
This does indeed seem to be an issue with iOS 10, there's quite a bit less spacing on iOS 11 (as intended).

**Comment by dgelessus** [comment] 2017-10-18 23:22
I just noticed something interesting related to this issue. It might have something to do with the system text size setting. For comparison, here are the main file list (with the huge spacing) and the Pythonista settings (with normal spacing) with system text size at minimum (which is what I use normally):

![img_0872](https://user-images.githubusercontent.com/6641959/31747060-fa18a10c-b46a-11e7-96b7-0540b9f22ac5.jpg) ![img_0873](https://user-images.githubusercontent.com/6641959/31747065-fd603e1a-b46a-11e7-9c3c-ccb7b42adaec.jpg)

And the same with system text size at maximum:

![img_0874](https://user-images.githubusercontent.com/6641959/31747081-14016892-b46b-11e7-8240-b4f00ef42d7c.jpg) ![img_0875](https://user-images.githubusercontent.com/6641959/31747085-16d6959c-b46b-11e7-811f-ffdf902fded6.jpg)

In the main file list, the height of spacing plus header text remains constant, no matter what the text size is. In the settings, the height of the spacing remains constant, but the total height changes when the header text height changes.

Another thing I've noticed (somewhat unrelated) is that in the file list, the cell title text changes size based on the system text size. However, in many other table views (like the Pythonista settings) it is always at the default ("medium") text size. That seems like a bug to me.

**Comment by omz** [comment] 2017-10-18 23:26
Interesting. To be honest, I haven’t really looked much at the system-level font size setting yet, and I wasn’t aware that it currently affects the library view in Pythonista.

**Comment by zrzka** [comment] 2017-10-19 08:12
Not just cells, see [this](https://developer.apple.com/videos/play/wwdc2017/245/) for example. It's called iOS Dynamic Type and it basically should change text size _everywhere_. I would expect it should change text size everywhere except Python code, where I can override it in Pythonista settings.

**Comment by omz** [comment] 2017-10-19 08:28
Yeah, I’m aware that I *should* support this eventually, but I’d like to do it in a somewhat consistent manner, not just in some random part of the app. That’s quite a bit of work, as I’d have to look at pretty much every piece of UI, and it’s unlikely that I’ll get to it for this release.

**Comment by zrzka** [comment] 2017-10-19 08:32
Agree, I don't see it as something with big priority. Personally, I don't use this feature at all. But also understand how it can be useful for people with some kind of health issues / disabilities.

**Comment by omz** [comment] 2017-10-19 08:37
The extraneous blank space should be fixed in the new beta (build 311014). Dynamic Text support should probably be a separate issue.

**Closed by omz** 2017-10-19 08:37 UTC
