### ISSUE TITLE
Can't import numpy with python 3.6

### ISSUE THREAD

**Issue by joelfrederico** [omz/Pythonista-Issues#570] opened 2018-10-13 07:19 UTC
Exactly what the comment says

**Comment by dgelessus** [comment] 2018-10-13 12:00
Try restarting Pythonista. There is a relatively common issue that can cause the numpy module to break temporarily, which can be fixed by restarting the app.

If that doesn't help, please include the exact error message that you get (copy-paste it if possible). Otherwise it's very difficult to tell what the problem is.

**Closed as completed** 2018-10-13 19:22 UTC
