### ISSUE TITLE
How can we prioritise issues to focus effort?

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#447] opened 2017-10-22 09:50 UTC
This repo currently has 325 open issues for only one Developer.

There a lot of "nice to have" issues that will never get resolved.  Could we use labels to mark those isseue where others is the community can contribute (documentation, tests, FAQ).  Could we also use either labels or "projects" to focus effort on the issues that are most important?  It would be nice to understand/plan out what should be in the next release and the release after that.  Of course, this is not a democracy and our Developer can change or ignore the suggestions.  Just because a lot of us might want a feature does not mean that it is doable or right for the product.  However it would be helpful to understand the priorities of then community a d where the help can be provided.

**Comment by zrzka** [comment] 2017-10-22 10:13
Trying to help with this now. Decided to go through all the open issues, check if they're still valid or not, close them, properly mark them with bug, enhancement, ... This will help me to understand what kind of issues are there. When I'll finish the 1st round (no idea when, as you said, there're more than 300 of them), I'll do another round and will probably introduce new labels based on knowledge from the 1st round, to provide better sorting of them somehow. That's probably all I can do now. Keep the list of open issues low, issues that are still valid, ... and then it's up to Ole how much he would like to open dev process in terms of what will be done, when, ... Question is how much time Ole wants to spend with this, because I can imagine, it can take quite some time and it can slow down development. Day has just 24h. Stepping into this thread, just to publicly state what I'm just trying to do with all these issues. If anyone wants to join my effor, feel free, we can coordinate it somehow to help Ole.

**Comment by Phuket2** [comment] 2017-10-23 08:03
Not sure it happens now or not, but I usually come back and look at what I have posted and then check to see if its fixed. If it is, I close the issue. That has some draw. Backs I guess, as I test on the device I have reported from. Normally you would think its ok to close.  But If I was commercial testing, you would want the test done on variety of devices and if applicable on both py3.5/6 2.7

Another possible help would be a standard preamble to the issue eg:
PYV:311014
IOS:iOS11.03
Device:IPad Pro 12.9 Rev2
PY: PY3.6 and PY2.7
Category:Keyboard
Issue: Blah, Blah

A this info could be collected automatically by a form inside Pythonista, with a free form area to write the comments. Then you could copy paste straight into a issue.  I think that I read that there is an api for Github issues. So a step further could be to post the issue from inside Pythonista. Oh course you still want to go to the issues to see if its been recorded already, or another step further would be able to browse the issues inside Pythonista before posting.  

Look, I am just thinking out aloud here.  Just seems if the data entry/reporting was more consistent it would be easier for someone to go though and help prioritise them.  This whole free form thing must be a nightmare for a developer.  
I am surprised GitHub hasn't dome more to help developers with this.  Eg. The definition of a custom issue template, Multiple issue lists etc....Seems a lot more could and should be done.
Oh well, thats my rant for the day :)

**Comment by zrzka** [comment] 2017-10-23 20:00
> This repo currently has 325 open issues for only one Developer.

299 even with four more issues filled in 😅

**Comment by TeamSpen210** [comment] 2017-10-24 01:08
You can define [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/), [guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) and other things by committing files under specific names.

**Comment by Phuket2** [comment] 2017-10-24 10:16
@TeamSpen210, that was a nice recommendation.  I followed the instructions and in my repo when I clicked new issue I got the below. Unfortunately I dont know much about md, I just typed some text, I am sure a md wizard could do a lot more.

![](https://dl.dropbox.com/s/souvmucqesri59c/File%2024-10-17%2C%2017%2014%2056.png?dl=1)

**Comment by zrzka** [comment] 2017-10-24 11:17
I'll do this with some proposal, but later when I'll finish my first round with issues. Be patient pls :)

**Comment by zrzka** [comment] 2017-10-24 13:37
Current status - 274 open issues, still ~125 issues to review in the first round. Have to leave and will be kind of away tomorrow (boring meetings). I expect that I'll finish this first round until the end of this week. Stay tuned :)

**Comment by zrzka** [comment] 2017-10-25 19:30
# Proposal

## First review round

In a couple of past days, I did review all opened issues. We had around 340 of them. I, and others, closed almost 100 of them. There’s 239 of them now. What kind of issues were closed?

* Fixed ones
* Feature requests that will never be implemented
* Obsolete issues
* Too broad / generic issues

How did I choose which one to close and which one not? As a long time iOS / macOS developer (10 years), I have pretty good knowledge about iOS, how to write applications, what’s important, what’s against Apple’s HIG (Human Interface Guidelines), etc. Another sort of closed issues contain feature requests about modules provided by the Pythonista (internal, not 3rd party) which are easily solvable by few lines of Python code (without hacking with `objc_util`). If they’ll be implemented, they can lower clarity, brevity and cause issues to newcomers (two ways how to do one thing for example, ability to pass different value types in one keyword arg, etc.).

> I’m human, making mistakes, did close some of them Ole would like to implement and these were reopened by Ole. Glad he did it. If I closed one of your issues and you disagree, please, comment it, can be discussed / reopened.

### Issue labels

As of 2017-10-25.

* `enhancement` - 162 open issues
* `bug` - 52 open issues
* `module request` - 19 open issues
* `documentation` - 15 open issues
* `autocomplete` - 7 open issues
* `crash` - 6 open issues
* `fixed in beta` - 1 open issue
* `duplicate`, `examples` - 0 open issues

Sum of these numbers is not 239 (current number of open issues), because multiple labels can be used on one issue.

### What type of issues are filled?

From what I saw, issues can be grouped into several categories:

* Pythonista application itself (including Python interpreter)
* Pythonista module (like `ui`, `contacts`, …)
* Pythonista 3rd party package / module (like `pyflakes`, …)
* Documentation, examples

World is not black and white and some of these issues can belong to several categories.

There’s another point of view, priority:

* Crashers, serious bugs - these issues simply do not allow you to use Pythnonista. Sometimes `major` label is used.
* Bugs, enhancements that should be solved, but you can use Pythonista even with them. Workarounds available, another way how to achieve your goal, … Sometimes `normal` label is used.
* Enhancements, nice to have, but they really have no priority and they may or may not be fixed. Sometimes `minor` label is used.

### Second review round

What I would like to do now? I’ll go through all issues again and will mark them with proper labels. Main goal is to make them easily searchable, sortable, … to keep focusing on important things and let other things for later.

### Labels proposal

TBH, I’m not fan of repositories with lot of labels. People have no idea how to use them (they can’t now, because GitHub doesn’t allow this), but sometimes even contributors have no clue. It’s good to have them written down somewhere.

Another issue with labels is that they do not fire notification even if you’re watching repository. It’s hard to track changes. From this point of view, I propose to remove `fixed in beta` label completely. If anything is fixed, Ole can close it directly. This produces notification, [OP] is notified, can ask for reopen or create a new issue. It’s not ideal, but it’s better to be notified compared to the silent label modification.

I also propose to remove `autocomplete`,  `examples` and `duplicate` labels. Autocompletion is part of the Pythonista (even when it uses Python module, users don’t care). `examples` label is part of the documentation group. And `duplicate`, because it’s faster two write _Dupe of #xyz_ in the issue when the issue is going to be closed and you’re not forced to go and play with labels. Also people tend to forgot to use this label anyway.

I introduced label `crash` and I propose to replace it with `major`. Then we can also add `minor` for nice to have issues.

Last change is about modules. There’s `module request` label. I would rename it to the `3rd-party-module`  and would introduce `internal-module` label for modules provided by the Pythonista (`ui`, …).

Here’s the final list of proposed labels:

* `documentation`
* `3rd-party-module`, `internal-module` 
* `bug`, `enhancement`
* `major`, `minor` 

From nine labels down to seven. Anyone can create bookmarks with GitHub search queries to filter and sort issues.

Why `-` instead of ` `. That’s because you have to use `""` in search queries if there’s a space `label:"internal module"`  vs `label:internal-module`. Why no `pythonista` or `normal` label? You can search for them via:

* `-label:3rd-party-module -label:internal-module` -> Pythonista
* `-label:major -label:minor` -> normal priority

And IMHO it’s better to have smaller amount of labels. 

## Workflow

In this way, we can help Ole to sort them out. Anyway, it’s still Ole who decides what and when it will be fixed. If wrong label is used, Ole can always change it, can reopen issue, …

Another help is, that when the bug will be fixed, Ole can just close the issue and is not forced to play with labels like `fixed in beta`. He can simply comment it and hit the _Comment and Close_ button.

## Conclusion

Nothing’s perfect, even this proposal. It’s better to start discussion with something. Comments?

## CONTRIBUTING.md

When this settles down, I’ll write down `CONTRIBUTING.md` for the `Pythonista-Issues` repository, where I’ll describe:

* How to file issues, what’s important, what’s not, from where to get version info, …, some links to articles _How to write good bug report_
* Describe how to use labels if anyone else joins me in this effort

## Open questions

Still unsure what's better:

* `major`, `minor` & `-label:major -label:minor` (instead of `normal`)
* `major`, `minor` and introduce `normal` label

Still unsure what's better:

* `3rd-party-module`, `internal-module` & `-label:3rd-party-module -label:internal-module`
* `3rd-party-module`, `internal-module` & introduce `application`

Still unsure about trashing `fixed in beta`.

**Keep fixed in beta - cons**

* Adding labels is silent change in terms of notifications, leads to repetitive polling and requires Ole to add label and comment, me for example to check statuses of all these issues repetitively too
* When the app is released, we will need to go through all issues with `fixed in beta`, close them, but carefully, because there can be another beta in the meanwhile and wrong issues can be closed (`fixed in beta` can be on more planned versions)

**Trash fixed in beta - cons**

* Ole think it's fixed, but it's not for example and user have to comment or fill new issue, because user can't even reopen own issues

I agree that it's more correct to use `fixed in beta` and close it later. But it's GitHub with limitations (two issue states open vs closed, no notifications when labels are modified, ...) and this must be kind of pragmatical decision - to keep amount of required work on both sides as small as possible. Here I'm for `fixed in beta` removal & closing issues, because of less work.

Yes, we can introduce Projects, we do use them at work, but not sure if it's worth to spend time with them. I mean, we should probably start with something smaller and enhance the whole process later.

@cclauss @omz & others, comments?

Agree? Use 👍 Disagree? Use 👎  Feel free to comment, but please, be brief, so, it will not be sooooooo long thread :)

**Comment by mikaelho** [comment] 2017-10-25 19:52
Thanks! You’ve done a tremendous job, and deserve some sort of a community award. I was going to suggest a funny hat, but do not want you to think I am not being sincere in my thanks.

+1 for just major and minor. That way, if you do not know about the labels, your bug gets placed in the ”normal” category, which is the right starting point, I think.

**Comment by TeamSpen210** [comment] 2017-10-25 20:28
One thing that might help (although I don't know how @omz might feel about it) is to move the Pythonista-specific modules to here, so people can propose bugfixes and enhancements directly. Not sure how well that'd work with matching with the extension module components, when Ole wants to add features, and when doing releases though.

It'd probably be good to exclude modules which wrap extension modules, but for example the `turtle`, `webbrowser`, `editor` and `dialogs' modules would be especially suitable (as they have lots of code not coupled to an extension module).

**Comment by zrzka** [comment] 2017-10-25 21:26
@mikaelho thanks, no offense taken :)) Since my another nick name is _no dog_, you can get me 3D printed [no dog](http://www.productstrategymeanssayingno.com) :))

@TeamSpen210 please, one thing at a time. This issue is about prioritizing issues, let's focus on it, thanks for understanding. What you propose really means substantial amount of work (repository, tests, documentation, guides, ...) and it's not just about moving pure Python modules somewhere. There're builtins, ObjC, ... You must have some environment to test all changes, CI, ... It's not that just easy as it sounds. Anyway, agree it can help, but it means lot of work from Ole's side. But leave this on Ole, maybe, sometimes we will be able to do what you propose. But just now, please, focus on prioritizing issues, thanks again.

**Comment by zrzka** [comment] 2017-10-27 14:30
C'mon, no one, just one thumb up and nothing more? If you'd like to say something, say it. Till Monday for example, then I'll finish contributing guide and will start labelling issues.

Just started working on README, REPORT, CONTRIBUTING, ... files and some scripts. Doing it in the [contributing](https://github.com/omz/Pythonista-Issues/tree/contributing) branch. Will be merged when it will be done and acked by Ole. There's just How to write a good bug report, sysinfo script for now. Contributing will contain label descriptions, how to help with testing and will also introduce report issue script.

**Comment by zrzka** [comment] 2017-10-27 15:20
@cclauss dude, that's not what I want to hear :) Label comments? Counter proposal? Or agree completely? (Thanks for the praise :)

Re sysinfo script - yup, it should be part of the Pythonista. But your one seems to contain lot of information (read - it's long) and it should be shorter. Something [like this](https://github.com/omz/Pythonista-Issues/blob/contributing/scripts/sysinfo.py), which produces ...

```
**System Information**

* Pythonista 3.1.1 (311015), Default interpreter 3.6.1
* iOS 11.0.3, model iPad, resolution (portrait) 2048.0 x 2732.0 @ 2.0
```

... is probably enough. Anyway, even if it will be added to the Pythonista, we should keep it in this repo as well, because older versions don't contain it.

**Comment by zrzka** [comment] 2017-10-30 08:29
Okay, since there're no more comments, here's [the pull request](https://github.com/omz/Pythonista-Issues/pull/465). It contains some guidelines, labels listed, links to search queries, ... @omz please, review it, merge it, ... Once this will be merged, feel free to create more pull requests to contributing guidelines, will review and merge them. At least proofreading of my English would be nice, ...

**Comment by zrzka** [comment] 2017-10-30 10:13
Just merged by Ole, thanks. And now we have a nice link to contributing guidelines 👍 

<img width="1015" alt="screen shot 2017-10-30 at 11 12 08" src="https://user-images.githubusercontent.com/1084172/32165502-4ee2d71a-bd63-11e7-9a26-0f7b228a94fd.png">

**Comment by zrzka** [comment] 2017-10-30 10:19
I just trashed the `contribution` branch. If anyone wants to add anything, feel free to fork this repository and create PR against `master`. Will try to help Ole by merging these PRs if they do contain reasonable additions. Go, go, we just started :)

2nd round of issue review just began :) Going to modify labels according to the contribution guide and will start adding them to all issues we have here.

**Comment by zrzka** [comment] 2017-11-02 15:05
2nd round done. TBH, I do not want to see issues for a couple of days :) Anyway, 235 issues and when you look at labels, it's not that bad in terms of bugs for example :)

<img width="998" alt="screen shot 2017-11-02 at 16 02 10" src="https://user-images.githubusercontent.com/1084172/32333109-574db2c2-bfe7-11e7-84ab-5d142cc5e5fe.png">

@cclauss happy? I mean, is there anything else to discuss? I mean, can we close this one? It seems that no one did join this discussion and I don't see a reason why to keep this one opened.

**Comment by jsbain** [comment] 2017-11-04 07:14
One though on the sysinfo -- maybe include an executable url?
[GetSysInfo](pythonista3://?exec=import%20plistlib%0Aimport%20os%0Aimport%20sys%0Aimport%20platform%0Afrom%20objc_util%20import%20ObjCClass,%20on_main_thread%0Aimport%20clipboard%0A%0A%0Adef%20get_pythonista_version_info():%0A%20%20%20%20version%20%3D%20None%0A%20%20%20%20bundle_version%20%3D%20None%0A%0A%20%20%20%20try:%0A%20%20%20%20%20%20%20%20plist_path%20%3D%20os.path.abspath(os.path.join(sys.executable,%20%27..%27,%20%27Info.plist%27))%0A%20%20%20%20%20%20%20%20plist%20%3D%20plistlib.readPlist(plist_path)%0A%0A%20%20%20%20%20%20%20%20version%20%3D%20plist%5B%27CFBundleShortVersionString%27%5D%0A%20%20%20%20%20%20%20%20bundle_version%20%3D%20plist%5B%27CFBundleVersion%27%5D%0A%0A%20%20%20%20except%20Exception:%0A%20%20%20%20%20%20%20%20pass%0A%0A%20%20%20%20return%20%27Pythonista%20%7B%7D%20(%7B%7D)%27.format(version%20or%20%27N/A%27,%20bundle_version%20or%20%27N/A%27)%0A%0A%0Adef%20get_python_interpreter_info():%0A%20%20%20%20return%20%27Default%20interpreter%20%7B%7D.%7B%7D.%7B%7D%27.format(*sys.version_info)%0A%0A%0Adef%20get_device_info():%0A%20%20%20%20device%20%3D%20ObjCClass(%27UIDevice%27).currentDevice()%0A%20%20%20%20main_screen%20%3D%20ObjCClass(%27UIScreen%27).mainScreen()%0A%20%20%20%20native_size%20%3D%20main_screen.nativeBounds().size%0A%0A%20%20%20%20return%20%27iOS%20%7B%7D,%20model%20%7B%7D,%20resolution%20(portrait)%20%7B%7D%20x%20%7B%7D%20@%20%7B%7D%27.format(%0A%20%20%20%20%20%20%20%20device.systemVersion(),%20platform.machine(),%0A%20%20%20%20%20%20%20%20native_size.width,%20native_size.height,%20main_screen.nativeScale()%0A%20%20%20%20)%0A%0A%0A@on_main_thread%20%20%23%20clipboard.set%20or%20freeze%0Adef%20main():%0A%20%20%20%20separator%20%3D%20%27---%20SYSTEM%20INFORMATION%20---%27%0A%0A%20%20%20%20info%20%3D%20%27%5Cn%27.join(%5B%0A%20%20%20%20%20%20%20%20%27**System%20Information**%27,%0A%20%20%20%20%20%20%20%20%27%27,%0A%20%20%20%20%20%20%20%20%27*%20%7B%7D,%20%7B%7D%27.format(get_pythonista_version_info(),%20get_python_interpreter_info()),%0A%20%20%20%20%20%20%20%20%27*%20%7B%7D%27.format(get_device_info()),%0A%20%20%20%20%5D)%0A%0A%20%20%20%20print(%27%5Cn%27.join(%5Bseparator,%20info,%20separator%5D))%0A%20%20%20%20print(%27Please,%20attach%20everything%20between%20%7B%7D%20to%20your%20GitHub%20issue,%20many%20thanks.%27.format(separator))%0A%20%20%20%20clipboard.set(info)%0A%20%20%20%20print(%27System%20information%20was%20just%20stored%20in%20the%20system%20clipboard.%20You%20can%20paste%20it%20with%20Cmd%20V.%27)%0A%0A%0Aif%20__name__%20%3D%3D%20%27__main__%27:%0A%20%20%20%20main()%0A)

**Comment by jsbain** [comment] 2017-11-04 07:31
[exec url](pythonista://exec?=import%20plistlib%0Aimport%20os%0Aimport%20sys%0Aimport%20platform%0Afrom%20objc_util%20import%20ObjCClass%2C%20on_main_thread%0Aimport%20clipboard%0A%0A%0Adef%20get_pythonista_version_info%28%29%3A%0A%20%20%20%20version%20%3D%20None%0A%20%20%20%20bundle_version%20%3D%20None%0A%0A%20%20%20%20try%3A%0A%20%20%20%20%20%20%20%20plist_path%20%3D%20os.path.abspath%28os.path.join%28sys.executable%2C%20%27..%27%2C%20%27Info.plist%27%29%29%0A%20%20%20%20%20%20%20%20plist%20%3D%20plistlib.readPlist%28plist_path%29%0A%0A%20%20%20%20%20%20%20%20version%20%3D%20plist%5B%27CFBundleShortVersionString%27%5D%0A%20%20%20%20%20%20%20%20bundle_version%20%3D%20plist%5B%27CFBundleVersion%27%5D%0A%0A%20%20%20%20except%20Exception%3A%0A%20%20%20%20%20%20%20%20pass%0A%0A%20%20%20%20return%20%27Pythonista%20%7B%7D%20%28%7B%7D%29%27.format%28version%20or%20%27N/A%27%2C%20bundle_version%20or%20%27N/A%27%29%0A%0A%0Adef%20get_python_interpreter_info%28%29%3A%0A%20%20%20%20return%20%27Default%20interpreter%20%7B%7D.%7B%7D.%7B%7D%27.format%28%2Asys.version_info%29%0A%0A%0Adef%20get_device_info%28%29%3A%0A%20%20%20%20device%20%3D%20ObjCClass%28%27UIDevice%27%29.currentDevice%28%29%0A%20%20%20%20main_screen%20%3D%20ObjCClass%28%27UIScreen%27%29.mainScreen%28%29%0A%20%20%20%20native_size%20%3D%20main_screen.nativeBounds%28%29.size%0A%0A%20%20%20%20return%20%27iOS%20%7B%7D%2C%20model%20%7B%7D%2C%20resolution%20%28portrait%29%20%7B%7D%20x%20%7B%7D%20%40%20%7B%7D%27.format%28%0A%20%20%20%20%20%20%20%20device.systemVersion%28%29%2C%20platform.machine%28%29%2C%0A%20%20%20%20%20%20%20%20native_size.width%2C%20native_size.height%2C%20main_screen.nativeScale%28%29%0A%20%20%20%20%29%0A%0A%0A%40on_main_thread%20%20%23%20clipboard.set%20or%20freeze%0Adef%20main%28%29%3A%0A%20%20%20%20separator%20%3D%20%27---%20SYSTEM%20INFORMATION%20---%27%0A%0A%20%20%20%20info%20%3D%20%27%5Cn%27.join%28%5B%0A%20%20%20%20%20%20%20%20%27%2A%2ASystem%20Information%2A%2A%27%2C%0A%20%20%20%20%20%20%20%20%27%27%2C%0A%20%20%20%20%20%20%20%20%27%2A%20%7B%7D%2C%20%7B%7D%27.format%28get_pythonista_version_info%28%29%2C%20get_python_interpreter_info%28%29%29%2C%0A%20%20%20%20%20%20%20%20%27%2A%20%7B%7D%27.format%28get_device_info%28%29%29%2C%0A%20%20%20%20%5D%29%0A%0A%20%20%20%20print%28%27%5Cn%27.join%28%5Bseparator%2C%20info%2C%20separator%5D%29%29%0A%20%20%20%20print%28%27Please%2C%20attach%20everything%20between%20%7B%7D%20to%20your%20GitHub%20issue%2C%20many%20thanks.%27.format%28separator%29%29%0A%20%20%20%20clipboard.set%28info%29%0A%20%20%20%20print%28%27System%20information%20was%20just%20stored%20in%20the%20system%20clipboard.%20You%20can%20paste%20it%20with%20Cmd%20V.%27%29%0A%0A%0Aif%20__name__%20%3D%3D%20%27__main__%27%3A%0A%20%20%20%20main%28%29%0A)

**Comment by cclauss** [comment] 2017-11-04 08:51
It would be nice to use the repo "Projects" capability to understand/plan out what should be in the next release and the release after that.

**Comment by zrzka** [comment] 2017-12-07 17:33
@cclauss missed this one, sorry, pretty busy these days. Anyway, it's Ole's responsibility and it's up to him to decide if he wants to share these things or not. I kinda like Projects on GH and we do use them at work. But it adds another burden, which can slow things down. Especially when all this is one man work. Thus I don't think we'll see Projects soon. And I can be wrong, of course :)

Anyway, I think that the purpose of this issue is fulfilled and going to close it.

**Closed by zrzka** 2017-12-07 17:33 UTC
