### ISSUE TITLE
entering date  field in dialog crashes the application

### ISSUE THREAD

**Issue by balachandrana** [omz/Pythonista-Issues#187] opened 2016-09-29 07:00 UTC
1. The following code crashes when you enter something in "date" field in the current beta version (ipad 4 32 bit device).  This code works in app store version.

~~~
import dialogs
import datetime

form_list = [dict(type = 'text', title = 'First Name',
                key = 'first', placeholder = 'Aaaa'),
            dict(type = 'date', title = 'Date Of Birth',
                key = 'DOB', value = datetime.date.today())]
x = dialogs.form_dialog(title = 'date test', fields=form_list)
print(x)

~~~

2. stash is still not working in current beta

3. async examples use to fail in last beta but now (in current beta) they seem to work.

**Comment by Phuket2** [comment] 2016-09-29 15:53
I tried this code on iPad Pro, iOS 10 , latest beta 3. Run as py 3.x and py 2.7. Soon as touch the date field in the dialog, it crashes

**Comment by omz** [comment] 2016-10-03 10:18
The `ui.DatePicker.date` attribute is currently completely broken, and since the `dialogs` module uses it, it's broken as well. This should be fixed in the next beta (I've found the cause of it now).

**Comment by omz** [comment] 2016-10-03 10:20
Closing this now, as it's the same underlying issue as #184.

**Closed by omz** 2016-10-03 10:20 UTC
Labels: bug
