### ISSUE TITLE
iOS 11 Files Support

### ISSUE THREAD

**Issue by leesavide** [omz/Pythonista-Issues#427] opened 2017-10-18 23:42 UTC
I think it’d be fairly useful to add iOS 11’s files support, given how easy it’d be to manage scripts that way. Any chance on adding this in soon?

**Comment by zrzka** [comment] 2017-10-19 08:09
@leesavide it's already there, I mean, introduced in 311013 Pythonista beta few days ago.

![a77ad57c-fd65-4696-803e-e679a002f7f8](https://user-images.githubusercontent.com/1084172/31760575-73a52f14-b4b5-11e7-9aed-d1f95e4968b6.jpeg)

**Comment by filippocld** [comment] 2017-10-22 16:38
I'd s issue since this was added in the beta

**Comment by cclauss** [comment] 2017-10-22 18:28
I agree.  A label “fixed in beta” should be added to issues that are but those issues should not be closed until they are tested and confirmed closed in an AppStore release.

**Comment by filippocld** [comment] 2017-10-22 18:44
Agree.

> Il giorno 22 ott 2017, alle ore 20:28, cclauss <notifications@github.com> ha scritto:
> 
> I agree. A label “fixed in beta” should be added to issues that are but those issues should not be closed until they are tested and confirmed closed in an AppStore release.
> 
> Sent from my iPhone
>

**Comment by zrzka** [comment] 2017-10-22 19:02
I'm going to close it now. Same way as Ole did with several other issues like https://github.com/omz/Pythonista-Issues/issues/412. Comment that it's fixed in the beta and closed. I think it's better to close them and keep the list short. If there will be a problem with file sharing, new issue can be filled.

**Closed by zrzka** 2017-10-22 19:02 UTC

**Comment by rigogsilva** [comment] 2017-11-21 02:03
How do I get the beta?
