### ISSUE TITLE
SCNGeometryPrimitiveType.Line

### ISSUE THREAD

**Issue by boustrephon** [omz/Pythonista-Issues#525] opened 2018-01-29 13:21 UTC
I have been looking for SCNGeometryPrimitiveType.Line in Pythonista SceneKit, but have not been able to find it. Am I missing something?

I tried to follow https://developer.apple.com/documentation/scenekit/scngeometryprimitivetype

load_framework('SceneKit')
SCNGeometryPrimitiveType, SCNMaterial, SCNMaterialProperty = map(ObjCClass, ['SCNGeometryPrimitiveType',' SCNMaterial', 'SCNMaterialProperty'])

**Comment by zrzka** [comment] 2018-01-29 15:26
`SCNGeometryPrimitiveType` is not a class and that's the reason why `ObjCClass` doesn't work. It's enum, integer constants and values for it can't be retrieved in this way (not even via `ctypes` & `in_dll`). You have to copy them from header file ...

```python
SCNGeometryPrimitiveTypeTriangles = 0
SCNGeometryPrimitiveTypeTriangleStrip = 1
SCNGeometryPrimitiveTypeLine = 2
SCNGeometryPrimitiveTypePoint = 3
SCNGeometryPrimitiveTypePolygon = 4
```

... or ...

```python
from enum import IntEnum

class SCNGeometryPrimitiveType(IntEnum):
    TRIANGLES = 0
    TRIANGLE_STRIP = 1
    LINE = 2
    POINT = 3
    POLYGON = 4
```

If you'd like to create polygon, you can do it in this way for example:

```python
load_framework('SceneKit')
SCNGeometryElement = ObjCClass('SCNGeometryElement')
IndiceValueType = c_uint32  # c_uint8, c_uint16 and c_uint32 supported, c_uint64 isn't

indices_count = 13
indices = [
    3, 4, 3, 3, 3, 4, 4, 4, 4, 4,
    4, 4, 4, 0, 1, 2, 3, 4, 5, 6,
    7, 1, 8, 8, 1, 0, 2, 1, 7, 9,
    8, 0, 10, 10, 0, 2, 11, 11, 2,
    7, 12, 12, 7, 8, 9, 9, 5, 4, 12,
    10, 6, 5, 9, 11, 3, 6, 10, 12,
    4, 3, 11
]

element = SCNGeometryElement.geometryElementWithData_primitiveType_primitiveCount_bytesPerIndex_(
    bytes((IndiceValueType * len(indices))(*indices)),
    SCNGeometryPrimitiveType.POLYGON,
    indices_count,
    sizeof(IndiceValueType)
)
```

Or replace `.POLYGON` with whatever value from `SCNGeometryPrimitiveType` enum.

Closing it because it's not a bug, rather an question. It's a thin ice when you decide to go this way (`objc_util`, `ctypes`, ...). AFAIK there's an issue requesting Python wrapper for the SceneKit.framework, but have no idea about time frame.

**Closed by zrzka** 2018-01-29 15:26 UTC

**Comment by zrzka** [comment] 2018-01-29 15:31
Here's the definition if you're interested ...

```objc
typedef NS_ENUM(NSInteger, SCNGeometryPrimitiveType) {
	SCNGeometryPrimitiveTypeTriangles                                                  = 0,
	SCNGeometryPrimitiveTypeTriangleStrip                                              = 1,
	SCNGeometryPrimitiveTypeLine                                                       = 2,
	SCNGeometryPrimitiveTypePoint                                                      = 3,
#if defined(SWIFT_SDK_OVERLAY2_SCENEKIT_EPOCH) && SWIFT_SDK_OVERLAY2_SCENEKIT_EPOCH >= 2
    SCNGeometryPrimitiveTypePolygon API_AVAILABLE(macos(10.12), ios(10.0), tvos(10.0)) = 4
#endif
};
```

**Comment by boustrephon** [comment] 2018-01-30 12:05
Thank you so much - I really appreciate you taking your time to explain this.
