### ISSUE TITLE
Broken output for Python Koans

### ISSUE THREAD

**Issue by StefanD986** [omz/Pythonista-Issues#253] opened 2017-01-16 12:03 UTC
I tried to work on the Python Koans (link below) with Pythonista, but when I run the "contemplate_kons.py" script the output text is broken:

Steps to reproduce:
1. Get python Koans code from https://github.com/gregmalcolm/python_koans and load into pythonista
2. Execute koans/python3/contemplate_koans.py
3. Check console output.

Expected console output:
```python
Thinking AboutAsserts
  test_assert_truth has damaged your karma.
 
You have not yet reached enlightenment ...
  AssertionError: False is not true
 
Please meditate on the following code:
  File "C:\Users\a0406985\PycharmProjects\python_koans\python3\koans\about_asserts.py", line 17, in test_assert_truth
    self.assertTrue(False) # This should be True
 
 
You have completed 0 (0 %) koans and 0 (out of 37) lessons.
You are now 302 koans and 37 lessons away from reaching enlightenment.
 
Beautiful is better than ugly.
```

Actual console output:
```python
[39m[22mThinking AboutAsserts
  [31m[1mtest_assert_truth has damaged your karma.

[39m[22mYou have not yet reached enlightenment ...
[31m[1m  AssertionError: False is not true

[39m[22mPlease meditate on the following code:
[33m[1m  File "/private/var/mobile/Containers/Shared/AppGroup/DA7FEF4F-5BB2-4913-82BB-4D40956F8FE8/Pythonista3/Documents/koans/python3/koans/[34mabout_asserts.py[33m", [34mline 17[33m, in test_assert_truth
    self.assertTrue(False) # This should be True[39m[22m


You have completed 0 (0 %) koans and 0 (out of 37) lessons.
You are now 302 koans and 37 lessons away from reaching enlightenment.

[36mBeautiful is better than ugly.[39m[22m
```

**Comment by cclauss** [comment] 2017-01-16 12:48
The line `self.assertTrue(False)` will ALWAYS throw an exception.  That would be the case on Pythonista and every other Python implementation.  Try running same on your Mac or PC.  My bet is that this was the expected behavior by the author for the koan and that it is an important step along your journey to zen enlightenment that you fix the offending code to avoid throwing this exception.

**Comment by omz** [comment] 2017-01-16 12:50
@cclauss I think this is about the control characters. It looks like `python_koans` might require a real terminal...

**Comment by StefanD986** [comment] 2017-01-16 17:09
Yes, I meant the additional control characters. The exceptions are expected (the purpose of the "Python Koans" scripts is to learn Python and Test driven development by fixing the exceptions step by step)

**Comment by jsbain** [comment] 2017-01-17 08:43
have you tried this using stash? i think stash emulates ansi color using pyte.

**Comment by controversial** [comment] 2017-08-06 14:03
Closing for now because Pythonista's interactive terminal isn't intended to support these control characters (at least at this point). Feel free to open a feature request for control character support in a new issue.

**Closed by controversial** 2017-08-06 14:03 UTC
