### ISSUE TITLE
open file read/write encoding error

### ISSUE THREAD

**Issue by danrcook** [omz/Pythonista-Issues#61] opened 2016-06-30 01:17 UTC
I have no idea if this is a bug. It may be just my lack of knowledge. I thought that utf-8 was fully supported in Python 3. But I get encoding errors with `open()`.

If it's not a bug just close the issue and I'm sorry for wasting anyone's time.

Anyway here's example code:

```
s = '•'

def w_r(s):
	#will give an encoding error
	with open('test.txt', 'w') as file:
		file.write(s)
		
	with open('test.txt', 'r') as file:
		print(file.read())
	
def w_r_encoded(s):
	#works
	with open('test.txt', 'w', encoding='utf-8') as file:
		file.write(s)
		
	with open('test.txt', 'r', encoding='utf-8') as file:
		print(file.read())
		
#w_r(s) #error
w_r_encoded(s) #works
```

**Comment by omz** [comment] 2016-06-30 01:28
I wouldn't really consider this a bug. When you open a file for writing in text mode, you should _always_ specify the encoding – otherwise, the encoding is platform-dependent, and you just don't really know what's being used... That said, I do think that utf-8 _should_ be the default in Python 3 (i.e. what's returned by `locale.getpreferredencoding`), and it currently isn't in Pythonista, so I'll leave this open for now.

**Comment by danrcook** [comment] 2016-06-30 01:29
@omz thank you!

**Comment by controversial** [comment] 2016-06-30 01:30
Closing as not a bug.

**Comment by controversial** [comment] 2016-06-30 01:31
Sorry, didn't see @omz's comment :grimacing:

**Comment by dgelessus** [comment] 2016-06-30 06:42
@omz I don't think the default should be UTF-8, it should be ASCII like in Python 3 on a normal computer. On my Mac for example, I cannot read/write non-ASCII characters from/to a file without setting an encoding by hand:

```python
>>> f = open("out.txt", "w")
>>> f.write("ütf-8")
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    f.write("ütf-8")
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 0: ordinal not in range(128)
```

**Comment by controversial** [comment] 2016-06-30 12:05
If this is the way it is on Desktop, we probably should close this.

**Comment by cclauss** [comment] 2016-06-30 12:20
Instead of closing this (i.e. sweeping it under the rug) it think it is useful to consider what @omz wrote:
> I do think that utf-8 should be the default in Python 3.

Perhaps it would be better to open this as a bug in upstream (i.e. in CPython).  Thoughts?  Why leave a razor blade lying on the table when you don't need to?

**Comment by omz** [comment] 2016-06-30 14:08
@dgelessus On my Mac, this works. What do you get from `locale.getpreferredencoding(False)`? I have to admit that I don't fully understand where this actually comes from. It's 'UTF-8' on my Mac with Python 3, but 'US-ASCII' both in Pythonista (2.7 and 3.5) and on my Mac with the system's Python 2.7.

**Comment by controversial** [comment] 2016-06-30 14:09
@omz I have the exact same behavior on my MBP

**Comment by dgelessus** [comment] 2016-06-30 15:34
Must be a locale-dependent thing. In IDLE I get this:

```python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> import locale
>>> locale.getlocale()
(None, None)
>>> locale.getpreferredencoding()
'US-ASCII'
```

In `python3` in the terminal I get this:

```python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> import locale
>>> locale.getlocale()
('de_DE', 'UTF-8')
>>> locale.getpreferredencoding()
'UTF-8'
```

**Comment by controversial** [comment] 2016-06-30 15:36
huh. I tested in the IPython terminal, IDLE is the enemy as far as I'm concerned.

**Comment by dgelessus** [comment] 2016-06-30 15:37
(Before anyone asks, passing `False` to `locale.getpreferredencoding` makes no difference.)

**Comment by omz** [comment] 2016-06-30 15:43
I guess at the very least, this confirms that it's _always_ a good idea to specify the encoding because the default can vary not just in Pythonista, but on other platforms as well... I'm having trouble getting `setlocale` and friends to behave properly on iOS – I'm not sure right now if this is iOS weirdness or just me not having a lot of experience with the locale-related APIs and environment variables.

**Comment by controversial** [comment] 2016-06-30 15:45
@omz I think a lot of people have complained about `locale` not working in the past. Also, aren't you taking a break? Deal with it later 😛

**Comment by omz** [comment] 2016-06-30 15:48
@controversial Yeah, I thought that there might be a quick solution, but it's apparently more complicated, and I'll deal with it later... I'm closing this now because it seems to me that the underlying problem is pretty much the same as issue #27.

**Closed by omz** 2016-06-30 15:48 UTC
Labels: enhancement
