### ISSUE TITLE
Editor makes unsolicited changes to entered text

### ISSUE THREAD

**Issue by mitlenatch** [omz/Pythonista-Issues#530] opened 2018-02-07 21:51 UTC
**Description**

This occurs after entering or editing a line of code in the Pythonista editor. After moving away from the line, or "popping down" the on-screen keyboard, some of the non-alphabetic characters (e.g. '(', ')', '_', ':', etc.) get "automatically" replaced by alphabetic ones.

For example, let's say I entered this line:
```    mystr = str(image.size) ```
Later, I notice it has been changed to:
```    mystr = strgimage.sizeh ```

In this example, '(' got replaced by 'g' and ')' got replaced by 'h'. There are others that I have found: '_' becomes 'f', ':' becomes 'j', and ''' (single quote) becomes 'm'. There may be more, but these are the ones I've identified so far.

Usually I don't notice the change until I run the script and get an error message that reports the bad line of code. Since the editor makes these unsolicited changes "automatically" and without any obvious user interaction, it has become a growing source of frustration for me, almost to the point where I'm considering editing all my code outside of Pythonista and importing it in.

**Steps to reproduce**

This bug occurs frequently, but unfortunately it's not 100% reproducible. The most reliable way I've found is to enter one or more lines of text, or edit an existing line, with the on-screen keyboard, then "pop-down" the on-screen keyboard. If it happens, you will see the aforementioned changes occur right before your eyes.

This is happening on an iPad Air (first gen) with iOS 10.2 using the "English" language locale.

I have not yet observed the bug when I was using a wireless (bluetooth) keyboard.

If others reading this have experienced the same problem, please add any information you have that might help isolate the cause. Thanks!

**System Information**

* Pythonista 3.2 (320000), Default interpreter 2.7.12
* iOS 10.2, model iPad4,1, resolution (portrait) 1536.0 x 2048.0 @ 2.0

**Comment by omz** [comment] 2023-01-27 19:53
I can't reproduce this, and the issue is quite old, so I'm closing it.

**Closed by omz** 2023-01-27 19:53 UTC
