### ISSUE TITLE
Designer- duplicating names - results in the view not being saved correctly

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#138] opened 2016-08-06 17:05 UTC
I think this is True. when in the Designer,  custom attributes as well as custom view class properties are not always saved correctly. It's very frustrating, because the memory version of the pyui file,  does not always reflect the file version.  Meaning the file version is behind the memory version.

I think the problem is in that the **Designer is creating views of the same name**. I am not 100 percent sure this is the problem, but I feel 95% sure of it. Sure you can change the names, I would say better to never duplicate a name in the designer 

So to me it would seem that the Designer  should never duplicate a name, subview or not.  I think this is causing problems. 

Personally, I think this is should be a high priority to fix/resolve

**Comment by jsbain** [comment] 2016-08-07 02:34
Can you be a little more specific?  i.e provide a sequence of operations to demonstrate the problem?

I know in the past, the designer did not save the pyui when you switched tabs, thus it was possible to get out of sync, if you tried to run from the console, or maybe when pressing play.

**Comment by Phuket2** [comment] 2016-08-08 10:53
@jsbain , I thought I found a simple case, then I tried to repeat it, could not make it happen. When I go looking for the bug, of course it eludes me.  But there definitely is a bug. It's so hard to find though.  It's likely to happen when you are not being very methodical. They are the easy ones to find, right.  I always try to at least close the current subview before switching tabs to run.  I am not sure when the designer decides to write out and if it's a lazy write or a flushed write. 

I will continue to look for a exact pattern though, I know it's there.  I am in the middle of trying to do something with these Custom View Classes and Custom Attributes at the moment. So hopefully I can come across a repeatable senerio to exactly illustrate the problem.

**Comment by zrzka** [comment] 2017-10-23 11:12
Removing `enhancement`, seems like `bug` report to me.

Anyway, no more comments, still open for more than one year, several new versions, ... @Phuket2 did you experience this issue again since your initial report? Also there's no steps to reproduce, quite hard to test it. I tried to do some crazy stuff in the designer, but wasn't able to see described behaviour.

**Comment by zrzka** [comment] 2017-11-02 13:41
No answer for more than 10 days, quite old, probably fixed in latest versions, closing.

**Closed by zrzka** 2017-11-02 13:41 UTC
Labels: bug, pythonista
