### ISSUE TITLE
Pythonista crashing when renaming folder

### ISSUE THREAD

**Issue by TheLukeGuy** [omz/Pythonista-Issues#175] opened 2016-09-19 22:11 UTC
Whenever I rename a folder inside of Pythonista, the app crashes.

**Comment by dgelessus** [comment] 2016-09-19 22:18
\*enable annoying tech support mode\*

* Pythonista 2 or 3?
* Which device and iOS version?
* Which Pythonista version (App Store or beta)?
* Anything special about the folder? Is it at the top level or in another folder? Any special characters in the name?
* Does this happen with other folders too (e. g. a newly created one)?

**Comment by TheLukeGuy** [comment] 2016-09-19 23:26
LOL, forgot to include all that in the original issue!
* Pythonista 2
* iPad mini 4 running iOS 10.0.1 (latest)
* App Store
* Nothing special, just in the regular documents folder
* Yes, it happens with all folders

**Comment by lukaskollmer** [comment] 2016-09-20 05:07
Hello @TheLukeGuy,

Engineering has determined that your bug report (#175) is a duplicate of another issue (#46) and will be closed.

(I already reported this about 3 months ago)

**Closed by lukaskollmer** 2016-09-20 05:07 UTC
